// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gittmcnmjyncsvpbfchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdHRtY25tanluY3N2cGJmY2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ4MzcsImV4cCI6MjA2NTUwMDgzN30.2gLmDxUx87s0q4ug4rRnyR4IDO3pyHf79dJuUeuY5q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);